# API Keys
[API_KEYS]
NANSEN_API_KEY = "HoNJHQ6CaDrqPg2Y6I06f7M9wFVIev0Q"
COINGECKO_API_KEY = "CG-Mp9EB3S8NQQed6dMfnyUyByW"
DUNE_API_KEY = "lfYVIFghe4zhlUf9m0J9ZdDRBvMByzes"
DEFILLAMA_API_KEY = ""

# Storage mode: local, gcs, bigquery, all
STORAGE_MODE = "all"

# GCP Service Account for Cloud Storage & BigQuery
[gcp_service_account]
type = "service_account"
project_id = "gfi-455410"
private_key_id = "c5f5b0bf4d3adfa92186741cc0b4c1808f5d9c1a"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCaF8rihcQEw0LS\ni0n7xzYdYqFXIJmHPx3sTW0VRdFXJFPePCVdRaurrjvqKqo0E5jteoQ1grKbFT3z\n+CqZdj5qM/WAXdQLm/pJ5D4R4OfyPGaKuCTNt68hW5Bbn6C5gPCs3pdqCcdpxvp1\nVij7Io3YgYlZlbNzvlJR8yK3Yx4SCNN2t0uXe92PGtDkeZJb6YDaDUM9lBDwRRel\nHleljOlApbWgAAXQcdiQg6L/jL4Uh+mA5nLnqymhMamDpFWOEH6QaSUR8AYKK32s\nUij47AWZALIAEhft07XQmKNABKHLfCMAMUbKzds0hHq1L0g35TrsgUIqc1QNv5vl\nJPVOqDtFAgMBAAECggEAAYeL7XyraeqwPpvAU73x9Q+2D0HVFEkVmHNaSlRDlCxZ\nosKREmBvKEiV8qiSwOqS4YSOTGOsNyraTxIfBh/s1awHW0tTH/xf2xznWtETLE3a\nLLVQNDSHCfs5LxeiBkVX3jdlZFmNf6jIcqK0zG1W4BfFD70TJ2pzsbmKlixnL4Gf\n+kxTOS1dQJDSwPsWva1J9QXOkoj3+bYjVRdDtdevjS1iM6u2P4wF+PpMzV+cmrig\n+6rIOksDzShGMEa9CvhEyd0vTG0PpfI+bdAJbJTxVAMLpCzH3sx7y5hzo3/JmNex\n3WtlIZbupIhuaQeDjClIVzJHSRleL0x2RcQFARI17wKBgQDId/gpKUnp1tkEsSLW\nszI+RIyQi4ye9liF0fKg51pnIyMjk1UaEwLP1LfbDSq5XYpeyc67+8NqLkLLbVmU\nxXBp9aCuG2jppaag8M0CFpFzG3Cn4tyX332+gQFynI3bVYOjQEb1ZkEZ37VXEAfN\nM9ky4dV+rkTaFFQJA8pZuAg0cwKBgQDExyNIaA+LdVMvQPpcHsRkG/2cU12gik9U\n7q5AcOgrlvGY6kQ856H9hGVZfVZq57KwLqAeZNMMtmVifpwXSALCGuRXofiedLJd\nmIIbbLyZl5YUQm30tdiV4LX9sakcZh02s89XGu6n9iIAoqBEo01b3+y0lCCXOkwP\n7/8zESEbZwKBgHFzO5UH0dWtijnWiXHaDeghYS94WkeoAKcTDu2yoH3X6835VmMg\nOSonJzmntPMcle9Y5E+MhqXzskdwBg9kwV6l7J470t7PqYJRZKP246+x6sqIX/Dv\nQTlrxsb3BG0JcysTeFTu3o7nBLhV0SR3YEckeW9s7nhAouJLK9wkgzgzAoGBALTE\nr5/7oJQfotxdF+F6jjXdFN0AJJmvlXNTlJY0YsRwdN9iDm/Y5pJLhwNvxeyNjzSU\nkJl7S/p4sKiL4P7uM0J3i98JN6jxUU30JUnmWVfLzp4r7HEKgL4m4Wj+RXmGQT4Y\nbtf5MNbxoIju3MZRMma9TekRzuK+NlPJyKn0CXLvAoGBAK/WENvwuu2VuTVetnMM\n0uTmjjzv4f6EXnjmOAHD/Sw92jqLjal3Qi+f1lnDzn5MFNesMFOXW/hbo3Q91Lqx\nLTPVCbq9IvHvzFSefMDtLiDogitRD6caBz/LZRr4sVMZQDiVcQHaHLZg7qPvPme1\nALmLY5O1boaoOC+OTt70fF8r\n-----END PRIVATE KEY-----\n"
client_email = "gcs-uploader@gfi-455410.iam.gserviceaccount.com"
client_id = "104833179090472317589"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gcs-uploader%40gfi-455410.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
